name: rag_cli
services:
  llm_embedding_backend:
    build:
      dockerfile: ./docker/Dockerfile.ollama
      target: ollama_embedding
    container_name: gnu_parallel_ollama_embedding
    ports:
      - 11434:11434
    volumes:
      - models:/home/ollama/.ollama/models

  llm_chat_backend:
    build:
      dockerfile: ./docker/Dockerfile.ollama
      target: ollama_chat
    container_name: gnu_parallel_ollama_chat
    ports:
      - 11435:11434
    volumes:
      - models:/home/ollama/.ollama/models

  vector_db:
    build:
      dockerfile: ./docker/Dockerfile.qdrant
      target: qdrant_prod
    ports:
      - 6333:6333
    container_name: gnu_parallel_vector_db
    volumes:
      - qdrant_storage:/home/qdrant/storage

volumes:
  models:
  qdrant_storage: