name: gnu_parallel
services:
  llm_backend:
    build:
      dockerfile: ./docker/Dockerfile.ollama
      target: ollama_env
    container_name: gnu_parallel_ollama
    ports:
      - 11434:11434
    volumes:
      - models:/home/ollama/.ollama/models

  vector_db:
    build:
      dockerfile: ./docker/Dockerfile.qdrant
      target: qdrant_env
    ports:
      - 6333:6333
    container_name: gnu_parallel_vector_db
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  models:
  qdrant_storage: