services:
  app:
    image: python:3.12
    volumes:
      - .:/home/coolguy/python_gnu_parallel
      - models:/home/coolguy/python_gnu_parallel/models
      - qdrant_storage:/home/coolguy/python_gnu_parallel/qdrant_storage
    
    # [Optional] Required for ptrac-based debuggers like C++, Go and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    # Overrides default command so things don't shut down after the process ends
    command: /bin/sh -c "while sleep 1000; do :; done"